# Generated by Django 4.1.7 on 2023-03-10 09:12

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
