# Generated by Django 4.1.7 on 2023-03-08 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytransaction',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='monthlytransaction',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='monthlytransaction',
            name='income',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transactiontype'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
